{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 2,
   "id": "e834c3ba-6f1a-45f4-862d-a3b7bb8a71a7",
   "metadata": {},
   "outputs": [],
   "source": [
    "from fastapi import FastAPI, HTTPException\n",
    "from contextlib import asynccontextmanager\n",
    "import pandas as pd\n",
    "import numpy as np\n",
    "import joblib\n",
    "import re\n",
    "\n",
    "# Initialize global variable for model artifacts\n",
    "model_artifacts = {}\n",
    "\n",
    "# =====================================================================\n",
    "# ⚙️ CONFIGURATION & SYSTEM PATHS\n",
    "# =====================================================================\n",
    "PICK_DATA_PATH    = '/home/adityaa/Desktop/internship/data/tbl_pick_summary.csv'\n",
    "SPACE_DATA_PATH   = '/home/adityaa/Desktop/internship/data/tblspace.csv'\n",
    "PUTAWAY_DATA_PATH = '/home/adityaa/Desktop/internship/data/putaway_summary.csv'\n",
    "MODEL_PATH        = '/home/adityaa/Desktop/internship/hybrid_production_model.pkl'\n",
    "SCORE_YEAR        = 2026\n",
    "\n",
    "# Helper function to validate zone strings cleanly\n",
    "def is_valid_warehouse_zone(zone_str):\n",
    "    if pd.isna(zone_str): return False\n",
    "    zone_str = str(zone_str).strip()\n",
    "    if zone_str.isdigit(): return False\n",
    "    if not re.match(r'^[A-Za-z0-9]+$', zone_str): return False\n",
    "    return True\n",
    "\n",
    "# =====================================================================\n",
    "# 1. LIFESPAN EVENT HANDLER (Loads model once on boot)\n",
    "# =====================================================================\n",
    "@asynccontextmanager\n",
    "async def lifespan(app: FastAPI):\n",
    "    \"\"\"Handles loading model artifacts safely into global memory on startup.\"\"\"\n",
    "    global model_artifacts\n",
    "    try:\n",
    "        model_artifacts = joblib.load(MODEL_PATH)\n",
    "        print(\"✅ API Boot Sequence: 2025 Model artifacts loaded securely.\")\n",
    "    except Exception as e:\n",
    "        print(f\"❌ API Boot Error: Model file could not be loaded. Details: {str(e)}\")\n",
    "    yield\n",
    "    print(\"🛑 API Shutdown Sequence: Closing resources.\")\n",
    "\n",
    "# Initialize FastAPI App with the Lifespan Context Handler\n",
    "app = FastAPI(title=\"Warehouse Zone Efficiency API\", lifespan=lifespan)\n",
    "\n",
    "# =====================================================================\n",
    "# 2. THE API ENDPOINT (The Production Interface)\n",
    "# =====================================================================\n",
    "@app.get(\"/api/get-efficiency\")\n",
    "def calculate_zone_efficiency():\n",
    "    \"\"\"\n",
    "    Triggers execution of the 2026 prediction workflow, matching incoming\n",
    "    metrics against frozen 2025 structural limits.\n",
    "    \"\"\"\n",
    "    try:\n",
    "        # Define base column matrices\n",
    "        table1_cols = [\"summary_id\" ,\"pickDate\", \"count\", \"itemCode\", \"itemDescription\", \"pickQty\", \"ordQty\", \"pickedStorageBin\", \"pickerId\", \"pickHeNo\", \"storageSectionId\", \"totalTimeSeconds\", \"perQtyTime\"]\n",
    "        table2_cols = [\"space_id\", \"st_sec_id\", \"totalCount\", \"usedCount\", \"createdDate\", \"utilization\"]\n",
    "\n",
    "        # Ingest fresh warehouse state arrays\n",
    "        table1 = pd.read_csv(PICK_DATA_PATH, header=None, names=table1_cols)\n",
    "        table2 = pd.read_csv(SPACE_DATA_PATH, header=None, names=table2_cols)\n",
    "        table3 = pd.read_csv(PUTAWAY_DATA_PATH, header=1, low_memory=False)\n",
    "        table3.columns = ['summary_id', 'putawayDate', 'count', 'itemCode', 'putAwayQty', 'ordQty', 'storageBin', 'storageSectionId', 'totalTimeinSeconds', 'perQtyTime', 'item_text', 'proposed_st_bin']\n",
    "\n",
    "        # Parse data timelines\n",
    "        table1['pickDate'] = pd.to_datetime(table1['pickDate'], errors='coerce')\n",
    "        table2['createdDate'] = pd.to_datetime(table2['createdDate'], errors='coerce')\n",
    "        table3['putaway_Date'] = pd.to_datetime(table3['putawayDate'], format='%Y-%m-%d', errors='coerce')\n",
    "\n",
    "        # Restrict datasets strictly to the targeting operational year\n",
    "        table1 = table1[table1['pickDate'].dt.year == SCORE_YEAR].copy()\n",
    "        table2 = table2[table2['createdDate'].dt.year == SCORE_YEAR].copy()\n",
    "        table3 = table3[table3['putaway_Date'].dt.year == SCORE_YEAR].copy()\n",
    "\n",
    "        # Sanitize text domains\n",
    "        table1 = table1[table1['storageSectionId'].apply(is_valid_warehouse_zone)]\n",
    "        table2 = table2[table2['st_sec_id'].apply(is_valid_warehouse_zone)]\n",
    "        table3 = table3[table3['storageSectionId'].apply(is_valid_warehouse_zone)]\n",
    "\n",
    "        # Filter structural outliers out of live system vectors\n",
    "        table1 = table1[(table1['totalTimeSeconds'] > 0) & (table1['totalTimeSeconds'] <= 7200) & (table1['pickQty'] >= 0) & (table1['ordQty'] > 0)]\n",
    "        table2 = table2[table2['totalCount'] > 0]\n",
    "        table3 = table3[(table3['totalTimeinSeconds'] > 0) & (table3['totalTimeinSeconds'] <= 3600) & (table3['putAwayQty'] > 0)]\n",
    "\n",
    "        # Create localized timelines strings\n",
    "        table1['pickMonth'] = table1['pickDate'].dt.strftime('%Y-%m')\n",
    "        table2['pickMonth'] = table2['createdDate'].dt.strftime('%Y-%m')\n",
    "        table3['pickMonth'] = table3['putaway_Date'].dt.strftime('%Y-%m')\n",
    "\n",
    "        # --- PARAMETER CALCULATION LAYER ---\n",
    "        # 1. Pick Rate\n",
    "        pr_df = table1.groupby(['pickMonth', 'storageSectionId']).agg(zone_picks=('pickQty', 'sum'), zone_time=('totalTimeSeconds', 'sum')).reset_index()\n",
    "        pr_df['zone_pick_rate'] = pr_df['zone_picks'] / (pr_df['zone_time'] + 0.001)\n",
    "        best_pr = pr_df.groupby('pickMonth')['zone_pick_rate'].max().reset_index().rename(columns={'zone_pick_rate': 'best_pick_rate'})\n",
    "        pr_df = pd.merge(pr_df, best_pr, on='pickMonth', how='left')\n",
    "        pr_df['Zone_Pick_Rate_Score'] = ((pr_df['zone_pick_rate'] / pr_df['best_pick_rate']) * 100).clip(upper=100.0)\n",
    "\n",
    "        # 2. Throughput\n",
    "        zt_df = table1.groupby(['pickMonth', 'storageSectionId']).agg(zone_units=('pickQty', 'sum'), zone_time=('totalTimeSeconds', 'sum')).reset_index()\n",
    "        zt_df['zone_throughput'] = zt_df['zone_units'] / (zt_df['zone_time'] + 0.001)\n",
    "        zt_df['Zone_Throughput_Score'] = ((zt_df['zone_throughput'] / model_artifacts['throughput_95th_ceiling_global']) * 100).clip(upper=100.0)\n",
    "\n",
    "        # 3. Picker Performance\n",
    "        sku_df = table1.groupby(['itemCode', 'pickMonth', 'storageSectionId']).agg(picks=('pickQty', 'sum'), time=('totalTimeSeconds', 'sum')).reset_index()\n",
    "        sku_df['actual_picker_rate'] = sku_df['picks'] / (sku_df['time'] + 0.001)\n",
    "        sku_df['Picker_Performance_Ratio'] = sku_df['actual_picker_rate'] / model_artifacts['warehouse_median_rate']\n",
    "        zone_picker_df = sku_df.groupby(['pickMonth', 'storageSectionId'])['Picker_Performance_Ratio'].mean().reset_index()\n",
    "        zone_picker_df['Zone_Picker_Performance_Score'] = (zone_picker_df['Picker_Performance_Ratio'] * 100).clip(upper=100.0)\n",
    "\n",
    "        # 4. Space Utilization\n",
    "        space_df = table2.groupby(['pickMonth', 'st_sec_id'])['utilization'].mean().reset_index().rename(columns={'st_sec_id': 'storageSectionId'})\n",
    "        space_df['Space_Score'] = space_df['utilization'].clip(upper=100.0)\n",
    "\n",
    "        # 5. Equipment Scores\n",
    "        equip_df = table1.groupby(['pickHeNo', 'pickMonth', 'storageSectionId']).agg(qty=('pickQty', 'sum'), time=('totalTimeSeconds', 'sum')).reset_index()\n",
    "        equip_df['machine_rate'] = equip_df['qty'] / (equip_df['time'] + 0.001)\n",
    "        machine_medians = equip_df.groupby('pickHeNo')['machine_rate'].median().reset_index().rename(columns={'machine_rate': 'baseline_rate'})\n",
    "        equip_df = pd.merge(equip_df, machine_medians, on='pickHeNo', how='left')\n",
    "        equip_df['machine_efficiency'] = equip_df['machine_rate'] / (equip_df['baseline_rate'] + 0.001)\n",
    "        zone_equip_df = equip_df.groupby(['pickMonth', 'storageSectionId'])['machine_efficiency'].mean().reset_index()\n",
    "        zone_equip_df['Zone_Equipment_Score'] = (zone_equip_df['machine_efficiency'] * 100).clip(upper=100.0)\n",
    "\n",
    "        # 6. Putaway Throughput\n",
    "        pt_df = table3.groupby(['pickMonth', 'storageSectionId']).agg(qty=('putAwayQty', 'sum'), time=('totalTimeinSeconds', 'sum')).reset_index()\n",
    "        pt_df['putaway_rate'] = pt_df['qty'] / (pt_df['time'] + 1e-5)\n",
    "        pt_df['Putaway_Throughput_Score'] = ((pt_df['putaway_rate'] / model_artifacts['putaway_75th_ceiling_global']) * 100).clip(upper=100.0)\n",
    "\n",
    "        # 7. Dock to Stock\n",
    "        d2s_df = table3.groupby(['pickMonth', 'storageSectionId']).agg(total_qty=('putAwayQty', 'sum'), total_time=('totalTimeinSeconds', 'sum')).reset_index()\n",
    "        d2s_df['weighted_d2s_seconds'] = d2s_df['total_time'] / (d2s_df['total_qty'] + 1e-5)\n",
    "        d2s_df['Dock_to_Stock_Score'] = ((model_artifacts['d2s_baseline_seconds'] / (d2s_df['weighted_d2s_seconds'] + 1e-5)) * 100).clip(upper=100.0)\n",
    "\n",
    "        # 8. Putaway Location Accuracy\n",
    "        table3['bin_match'] = (table3['storageBin'] == table3['proposed_st_bin']).astype(int)\n",
    "        acc_df = table3.groupby(['pickMonth', 'storageSectionId']).agg(matches=('bin_match', 'sum'), total=('bin_match', 'count')).reset_index()\n",
    "        acc_df['Putaway_Location_Accuracy_Score'] = (acc_df['matches'] / acc_df['total']) * 100\n",
    "\n",
    "        # --- ASSEMBLING UNIFIED MATRIX ---\n",
    "        features_to_cluster = model_artifacts['features_to_cluster']\n",
    "        df_new = pr_df[['pickMonth', 'storageSectionId', 'Zone_Pick_Rate_Score']].copy()\n",
    "        \n",
    "        # Execute vectorized left joins sequentially via a loop\n",
    "        for df_merge, col in zip([zt_df, zone_picker_df, space_df, zone_equip_df, pt_df, d2s_df, acc_df], features_to_cluster[1:]):\n",
    "            df_new = pd.merge(df_new, df_merge[['pickMonth', 'storageSectionId', col]], on=['pickMonth', 'storageSectionId'], how='left')\n",
    "\n",
    "        # Handle structural gaps using nested median tracking values\n",
    "        for col in features_to_cluster:\n",
    "            zone_medians = df_new.groupby('storageSectionId')[col].transform('median')\n",
    "            df_new[col] = df_new[col].fillna(zone_medians).fillna(df_new[col].median())\n",
    "\n",
    "        # --- MODEL SCORING PIPELINE ---\n",
    "        X_raw = df_new[features_to_cluster].values\n",
    "        X_scaled = model_artifacts['scaler'].transform(X_raw)\n",
    "        X_weighted = X_scaled * np.sqrt(model_artifacts['weights'])\n",
    "        \n",
    "        kmeans = model_artifacts['kmeans_model']\n",
    "        labels = kmeans.predict(X_weighted)\n",
    "        distances = kmeans.transform(X_weighted)\n",
    "        df_new['Assigned_Cluster'] = labels\n",
    "\n",
    "        # --- PIECEWISE GEOMETRIC SEGMENTATION SCORING LAYER ---\n",
    "        t1_idx = model_artifacts['tier_mapping']['t1_idx']\n",
    "        t2_idx = model_artifacts['tier_mapping']['t2_idx']\n",
    "        t3_idx = model_artifacts['tier_mapping']['t3_idx']\n",
    "        cluster_names = {t1_idx: 'Tier 1: High Efficiency', t2_idx: 'Tier 2: Moderate Efficiency', t3_idx: 'Tier 3: Low Efficiency'}\n",
    "\n",
    "        final_scores, final_tiers = [], []\n",
    "        for i, row in df_new.iterrows():\n",
    "            cluster = row['Assigned_Cluster']\n",
    "            \n",
    "            # Absolute Floor Override\n",
    "            if (row['Zone_Pick_Rate_Score'] <= 5.0 and row['Zone_Throughput_Score'] <= 5.0) and (row['Dock_to_Stock_Score'] <= 10.0 and row['Putaway_Throughput_Score'] <= 10.0):\n",
    "                final_scores.append(0.0)\n",
    "                final_tiers.append(cluster_names[t3_idx])\n",
    "                continue\n",
    "            # Absolute Ceiling Override\n",
    "            if (row['Zone_Pick_Rate_Score'] >= 82.0 and row['Zone_Throughput_Score'] >= 89.0) and (row['Dock_to_Stock_Score'] >= 85.0 and row['Putaway_Throughput_Score'] >= 85.0):\n",
    "                final_scores.append(100.0)\n",
    "                final_tiers.append(cluster_names[t1_idx])\n",
    "                continue\n",
    "\n",
    "            d1, d2, d3 = distances[i, t1_idx], distances[i, t2_idx], distances[i, t3_idx]\n",
    "            if cluster == t3_idx: \n",
    "                score = 33.33 * (1 - (d3 / (d3 + d2 + 1e-5)))\n",
    "            elif cluster == t2_idx: \n",
    "                score = 33.33 + (16.67 * (d3 / (d2 + d3 + 1e-5))) if d3 < d1 else 50.00 + (16.66 * (1 - (d2 / (d1 + d2 + 1e-5))))\n",
    "            else: \n",
    "                score = 66.66 + (33.34 * (d2 / (d1 + d2 + 1e-5)))\n",
    "            \n",
    "            final_scores.append(score)\n",
    "            final_tiers.append(cluster_names[cluster])\n",
    "\n",
    "        df_new['Zone_Efficiency_Score'] = final_scores\n",
    "        df_new['Zone_Efficiency_Tier'] = final_tiers\n",
    "\n",
    "        # Strip unneeded parameters out of the payload response matrix\n",
    "        output_cols = ['pickMonth', 'storageSectionId'] + features_to_cluster + ['Zone_Efficiency_Score', 'Zone_Efficiency_Tier']\n",
    "        final_df = df_new[output_cols].copy()\n",
    "        \n",
    "        # Round floating values cleanly\n",
    "        numeric_cols = final_df.select_dtypes(include=[np.number]).columns\n",
    "        final_df[numeric_cols] = final_df[numeric_cols].round(2)\n",
    "\n",
    "        # Stream payload back to the mediator database endpoint\n",
    "        json_payload = final_df.to_dict(orient=\"records\")\n",
    "        return {\n",
    "            \"status\": \"success\",\n",
    "            \"year_scored\": SCORE_YEAR,\n",
    "            \"total_records\": len(final_df),\n",
    "            \"data\": json_payload\n",
    "        }\n",
    "\n",
    "    except Exception as e:\n",
    "        raise HTTPException(status_code=500, detail=str(e))"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "44137b91-6df7-458c-aeb9-0ed64efe3fdf",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python (jupyter-env)",
   "language": "python",
   "name": "jupyter-env"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.12.3"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
